<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo $this->configApp->site->title; ?></title>


    <link rel="shortcut icon" href="/Assets/images/favicon.gif" type="image/gif">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/Assets/js/jquery.min.js">\x3C/script>')</script>


    <link rel="stylesheet" href="/Assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/Assets/css/application.css">

    <script src="/Assets/js/bootstrap.min.js"></script>

    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>


  <body>

<?php echo $this->module('top'); ?>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           <ul class="list-inline box-logo">
            <li class="logo"><a class="navbar-brand" href="/"></a></li>
          </ul>
        </div>
        <div class="navbar-collapse collapse">
<?php

if (!empty($allNewsSections)):
  echo '<ul class="nav navbar-nav">';
foreach ($allNewsSections as $key => $value):
  echo "<li class='active'><a href='/section/{$key}'>{$value}</a></li>";
endforeach;
  echo '</ul>';
endif;
?>


          <form class="navbar-form navbar-right" role="search" action="/search" method="post">
            <div class="form-group">
              <input type="text" name="phrase" class="form-control" placeholder="Buscar">
            </div>
            <button type="submit" class="btn btn-default">Buscar</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
<?php echo $this->module('menu'); ?>
    </div>

<?php echo $this->module('jumboBanner'); ?>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <?php echo $this->module('topContent'); ?>
        <?php echo $content; ?>
        <?php echo $this->module('bottomContent'); ?>
        </div>
      </div>
    </div> <!-- /container -->

<?php echo $this->module('bottomBanner'); ?>

    <div class="container">
      <footer>
      <?php echo $this->module('footer'); ?>
        <div class="col-md-9 footer-left">
            <a href="http://www.portalgenteactiva.com" class="logo fleft mr10">IB</a>
            <p class="mr10">&copy; <?php echo date('Y'); ?> - Todos los derechos reservados.</p>
            <ul class="clearfix">
         </div>
         <div class="col-md-2 copyright  footer-right">
            <p><a href="http://www.blacksur.com/" target="_blank" title="Diseñado por Black Sur"></a></p>
          </div>
      </footer>
    </div> <!-- /container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

  </body>
</html>
