<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo $this->configApp->site->title; ?></title>


    <link rel="shortcut icon" href="/Assets/images/favicon.gif" type="image/gif">

    <link rel="stylesheet" href="/Assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/Assets/css/application.css">
    <link rel="stylesheet" href="/Assets/css/fileAjax.css">
    <link rel="stylesheet" href="/Assets/css/entity.browse.css">

    <?php
    if (!empty($this->styles)) {
        foreach ($this->styles as $css) {
          echo "    <link href='{$css}' rel='stylesheet' type='text/css'>\n";
        }
    }
    ?>

    <?php
    if (!empty($this->javascripts)) {
        foreach ($this->javascripts as $js) {
          echo "<script type='text/javascript' src='{$js}'></script>\n";
        }
    }
    ?>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="/Assets/js/admin.js"></script>
    <script src="/Assets/js/bootstrap.min.js"></script>

    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>


  <body>

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="col-md-12">
        <div class="navbar-header">

          <a class="navbar-brand" href="/admin">Black FrameWork</a>
        </div>
        <div class="navbar-collapse collapse">

        </div><!--/.navbar-collapse -->
      </div>
    </div>

    <div class="col-md-12">
      <div class="row">
        <div class="col-md-3">
        <ul id="active" class="nav navbar-nav side-nav">
            <li class="selected"><a href="/admin"><i class="fa fa-bullseye"></i>ESCRITORIO</a></li>
            <li><a href="/admin/entities" role="button">Entities</a></li>
            <li><a href="/admin/entity/browse/News" role="button">Noticias</a></li>
            <li><a href="/admin/entity/browse/Module" role="button">Modulos</a></li>
        </ul>

        </div><!-- col-md-3 -->
        <div class="col-md-9">
<?php
$flashMessages = \Black\FlashMessage\FlashMessage::getSuccessMessages();
if (is_array($flashMessages)) {
  foreach ($flashMessages as $message) {
    echo "<p class='bg-success text-success'>{$message}</p>";
  }
}

$flashMessages = \Black\FlashMessage\FlashMessage::getErrorMessages();
if (is_array($flashMessages)) {
  foreach ($flashMessages as $message) {
    echo "<p class='bg-danger text-danger'>{$message}</p>";
  }
}
?>

        <?php echo $content; ?>
        </div><!-- col-md-9 -->
      </div><!-- row -->


      <hr>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div> <!-- /col-md-12 -->

  </body>
</html>
